title: Byzapp Labs Page
author: Gonçalo Videira
email: gvideira@byzapplabs.com
description: > # this means to ignore newlines until "baseurl:"
  Byzapp Labs page, built on github with public code.

# social links
twitter_username: videira_goncalo # DO NOT include the @ character, or else the build will fail!
github_username:  goncalovideira # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
